[package]
name = "alexandria"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-extra = "0.10.1"
chrono = "0.4.41"
colored = "3.0.0"
dotenvy = "0.15.7"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
sqlx = {version = "0.8.6", features = ["postgres"]}
tokio = {version = "1.47.1", features = ["full"]}
