[package]
name = "alexandria"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-extra = "0.10.1"
chrono = {version = "0.4.41", features = ["serde"]}
colored = "3.0.0"
ron = "0.10.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
sqlx = {version = "0.8.6", features = ["postgres", "chrono", "runtime-tokio-rustls"]}
tokio = {version = "1.47.1", features = ["full"]}
