chain_width                 = 50
comment_width               = 60
max_width                   = 80
wrap_comments               = true
reorder_impl_items          = true
newline_style               = "Unix"
style_edition               = "2024"