chain_width                 = 60
comment_width               = 75
max_width                   = 80
wrap_comments               = true
reorder_impl_items          = true
format_strings              = true
hard_tabs                   = true
newline_style               = "Unix"
style_edition               = "2024"