use std::num::NonZeroU16;

use axum::{
    http::StatusCode,
    response::{IntoResponse, Response},
};
use serde::{Deserialize, Serialize};

/// Based on RFC 9457
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct ProblemDetailJsonObject<T: Clone> {
    /// The "type" member is a JSON string containing a URI reference
    /// that identifies the problem type. Consumers MUST use the "type" URI
    /// (after resolution, if necessary) as the problem type's primary
    /// identifier.
    ///
    /// When this member is not present, its value is assumed to be
    /// "about:blank".
    ///
    /// If the type URI is a locator (e.g., those with an "http" or "https"
    /// scheme), dereferencing it SHOULD provide human-readable documentation
    /// for the problem type (e.g., using HTML). However, consumers
    /// SHOULD NOT automatically dereference the type URI, unless they do so
    /// when providing information to developers (e.g., when a debugging tool
    /// is in use).
    ///
    /// When "type" contains a relative URI, it is resolved relative to the
    /// document's base URI. However, using relative
    /// URIs can cause confusion, and they might not be handled correctly by
    /// all implementations.
    #[serde(rename = "type")]
    pub type_: String,

    /// The "status" member is a JSON number indicating the HTTP status code
    /// generated by the origin server for this occurrence
    /// of the problem.
    ///
    /// The "status" member, if present, is only advisory; it conveys the HTTP
    /// status code used for the convenience of the consumer. Generators MUST
    /// use the same status code in the actual HTTP response, to assure that
    /// generic HTTP software that does not understand this format still
    /// behaves correctly. See Section 5 for further caveats regarding its use.
    ///
    /// Consumers can use the status member to determine what the original
    /// status code used by the generator was when it has been changed (e.g.,
    /// by an intermediary or cache) and when a message's content is persisted
    /// without HTTP information. Generic HTTP software will still use the HTTP
    /// status code.
    pub status: NonZeroU16,

    /// The "title" member is a JSON string containing a short, human-readable
    /// summary of the problem type.
    ///
    /// It SHOULD NOT change from occurrence to occurrence of the problem,
    /// except for localization (e.g., using proactive content negotiation).
    ///
    /// The "title" string is advisory and is included only for users who are
    /// unaware of and cannot discover the semantics of the type URI (e.g.,
    /// during offline log analysis).
    pub title: String,

    /// The "detail" member is a JSON string containing a human-readable
    /// explanation specific to this occurrence of the problem.
    ///
    /// The "detail" string, if present, ought to focus on helping the client
    /// correct the problem, rather than giving debugging information.
    ///
    /// Consumers SHOULD NOT parse the "detail" member for information;
    /// extensions are more suitable and less error-prone ways to obtain such
    /// information.
    pub detail: String,

    /// Reference to the specific problem.
    pub instance: String,

    /// Extra info about the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extra: Option<T>,
}

impl<T> ProblemDetailJsonObject<T>
where
    T: Clone,
{
    pub fn new() -> Self {
        Self {
            type_: "about:blank".into(),
            status: NonZeroU16::new(500).unwrap(),
            title: "Erro interno no servidor".into(),
            detail: "".into(),
            instance: "".into(),
            extra: None,
        }
    }

    pub fn status_code(&self) -> StatusCode {
        StatusCode::from_u16(self.status.get())
            .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Serialize, Deserialize, Clone, Debug)]
    struct TestPayload;

    #[test]
    fn test_status_code_parse() {
        let problem: ProblemDetailJsonObject<TestPayload> =
            ProblemDetailJsonObject {
                type_: "".into(),
                status: NonZeroU16::new(404).unwrap(),
                title: "Not Found".into(),
                detail: "The requested resource was not found.".into(),
                instance: "https://example.com/instance/1".into(),
                extra: None,
            };

        assert_eq!(problem.status_code(), StatusCode::NOT_FOUND);
    }

    #[test]
    fn test_invalid_status_code_parse() {
        let problem: ProblemDetailJsonObject<TestPayload> =
            ProblemDetailJsonObject {
                type_: "".into(),
                status: NonZeroU16::new(1_000).unwrap(),
                title: "Not Found".into(),
                detail: "The requested resource was not found.".into(),
                instance: "https://example.com/instance/1".into(),
                extra: None,
            };

        assert_eq!(problem.status_code(), StatusCode::INTERNAL_SERVER_ERROR);
    }
}
