DROP TABLE IF EXISTS RelacaoReclamacaoAudiencia CASCADE;
DROP TABLE IF EXISTS RelacaoReclamacaoReclamado CASCADE;
DROP TABLE IF EXISTS HistoricoStatusReclamacao CASCADE;
DROP TABLE IF EXISTS Reclamacao CASCADE;
DROP TABLE IF EXISTS Audiencia CASCADE;
DROP TABLE IF EXISTS Reclamado CASCADE;
DROP TABLE IF EXISTS Reclamante CASCADE;
DROP TABLE IF EXISTS Procurador CASCADE;
DROP TABLE IF EXISTS Funcionario CASCADE;
DROP TABLE IF EXISTS Endereco CASCADE;
DROP TABLE IF EXISTS Diretorio CASCADE;
DROP TABLE IF EXISTS Motivo CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS Cargo CASCADE;

DROP FUNCTION IF EXISTS trigger_set_timestamp();
DROP TYPE IF EXISTS meio_audiencia_enum;